//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRM.DataAccesslayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetail
    {
        public int ProjectID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> WorkType { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProjectDetails { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<int> WorkStatus { get; set; }
        public string PointOfContact { get; set; }
    }
}
